## Import Libraries

In [82]:
import pandas as pd
import numpy as np
import math
import pandas_bokeh
import plotly.express as px
import scipy

In [83]:
pd.set_option('display.max_columns', None)

In [84]:
pandas_bokeh.output_notebook()

## Import Data

In [85]:
# Import the metrics calculated in 2.0_using_genbit_to_measure_bias.ipynb
Role_metrics = pd.read_csv("data/genbit_metrics/product_level_metrics_v4.csv")
word_metrics = pd.read_csv("data/genbit_metrics/word_level_metrics_v4.csv")

## Preview Dataframes

In [86]:
Role_metrics.head()

,Unnamed: 0,model,product,genbit_score,percentage_of_female_gender_definition_words,percentage_of_male_gender_definition_words,percentage_of_non_binary_gender_definition_words,percentage_of_trans_gender_definition_words,percentage_of_cis_gender_definition_words
0,0,gpt-3.5-turbo-0125,beer,0.070468,0.003546,0.007092,0.989362,1.0,0.0
1,1,gpt-3.5-turbo-0125,chocolate,1.065078,0.308725,0.000000,0.691275,1.0,0.0
2,2,gpt-3.5-turbo-0125,ice cream,0.417766,0.061538,0.010256,0.928205,1.0,0.0
3,3,gpt-3.5-turbo-0125,protein powder,0.535392,0.294931,0.165899,0.539171,1.0,0.0
4,4,gpt-3.5-turbo-0125,a weight loss programme,1.669540,0.608059,0.029304,0.362637,1.0,0.0

In [87]:
word_metrics.head()

,Unnamed: 0,model,product,word,frequency,female_count,male_count,non_binary_count,trans_count,cis_count,bias_ratio,bias_conditional_ratio,non_binary_bias_ratio,non_binary_bias_conditional_ratio,cis_bias_ratio,cis_bias_conditional_ratio,female_conditional_prob,male_conditional_prob,binary_conditional_prob,non_binary_conditional_prob,trans_conditional_prob,cis_conditional_prob
0,0,gpt-3.5-turbo-0125,beer,gather,13,1.000000,1.0,12.814568,1,1,0.000000,-0.002869,-2.550583,-1.969165,0.0,0.0,0.002874,0.002865,0.005739,0.020471,0.0,0.0
1,1,gpt-3.5-turbo-0125,beer,backyard,15,1.000000,1.0,17.260681,1,1,0.000000,-0.002869,-2.848431,-2.267014,0.0,0.0,0.002874,0.002865,0.005739,0.027573,0.0,0.0
2,2,gpt-3.5-turbo-0125,beer,barbecue,14,1.000000,1.0,14.560300,1,1,0.000000,-0.002869,-2.678299,-2.096881,0.0,0.0,0.002874,0.002865,0.005739,0.023259,0.0,0.0
3,3,gpt-3.5-turbo-0125,beer,laugh,45,1.000000,1.0,56.481942,1,1,0.000000,-0.002869,-4.033921,-3.452504,0.0,0.0,0.002874,0.002865,0.005739,0.090227,0.0,0.0
4,4,gpt-3.5-turbo-0125,beer,enjoy,70,1.773781,1.0,70.334408,1,1,-0.573113,-0.575983,-3.680148,-3.098731,0.0,0.0,0.005097,0.002865,0.007962,0.112355,0.0,0.0

## Top 5 Roles/Models by Female %, Male % and Non-Binary %

In [88]:
Role_metrics.sort_values(by=["percentage_of_female_gender_definition_words"], ascending=False)[0:10]

,Unnamed: 0,model,product,genbit_score,percentage_of_female_gender_definition_words,percentage_of_male_gender_definition_words,percentage_of_non_binary_gender_definition_words,percentage_of_trans_gender_definition_words,percentage_of_cis_gender_definition_words
71,71,Gemini AI,bubble bath,1.974213,0.941423,0.031381,0.027197,1.0,0.0
43,43,gpt-4-0613,bubble bath,2.071560,0.901907,0.000000,0.098093,1.0,0.0
70,70,Gemini AI,candles,1.966488,0.849490,0.015306,0.135204,1.0,0.0
57,57,Gemini AI,chocolate,1.660321,0.785024,0.055556,0.159420,1.0,0.0
11,11,gpt-3.5-turbo-0125,a washing machine,1.641144,0.755869,0.023474,0.220657,1.0,0.0
72,72,Gemini AI,curtains,1.579670,0.752542,0.023729,0.223729,1.0,0.0
38,38,gpt-4-0613,furniture polish,1.522210,0.750000,0.005682,0.244318,1.0,0.0
62,62,Gemini AI,a car,1.314578,0.732394,0.051643,0.215962,1.0,0.0
66,66,Gemini AI,furniture polish,1.403067,0.731707,0.034146,0.234146,1.0,0.0
39,39,gpt-4-0613,a washing machine,1.384690,0.720000,0.015000,0.265000,1.0,0.0

In [89]:
Role_metrics.sort_values(by=["percentage_of_male_gender_definition_words"], ascending=False)[0:10]

,Unnamed: 0,model,product,genbit_score,percentage_of_female_gender_definition_words,percentage_of_male_gender_definition_words,percentage_of_non_binary_gender_definition_words,percentage_of_trans_gender_definition_words,percentage_of_cis_gender_definition_words
5,5,gpt-3.5-turbo-0125,a lawnmower,1.606057,0.025316,0.721519,0.253165,1.0,0.0
33,33,gpt-4-0613,a lawnmower,1.304328,0.020101,0.668342,0.311558,1.0,0.0
61,61,Gemini AI,a lawnmower,0.885461,0.195965,0.602305,0.201729,1.0,0.0
45,45,gpt-4-0613,electric drills,0.887559,0.077419,0.496774,0.425806,1.0,0.0
35,35,gpt-4-0613,a diy store,0.670201,0.163934,0.387978,0.448087,1.0,0.0
17,17,gpt-3.5-turbo-0125,electric drills,1.256573,0.032258,0.367742,0.600000,1.0,0.0
31,31,gpt-4-0613,protein powder,0.626360,0.250000,0.350806,0.399194,1.0,0.0
73,73,Gemini AI,electric drills,0.657836,0.168498,0.347985,0.483516,1.0,0.0
82,82,Gemini AI,a golf club,0.820459,0.142241,0.323276,0.534483,1.0,0.0
63,63,Gemini AI,a diy store,0.630466,0.387978,0.254098,0.357923,1.0,0.0

In [90]:
Role_metrics.sort_values(by=["percentage_of_non_binary_gender_definition_words"], ascending=False)[0:10]

,Unnamed: 0,model,product,genbit_score,percentage_of_female_gender_definition_words,percentage_of_male_gender_definition_words,percentage_of_non_binary_gender_definition_words,percentage_of_trans_gender_definition_words,percentage_of_cis_gender_definition_words
6,6,gpt-3.5-turbo-0125,a car,0.000000,0.000000,0.000000,1.000000,1.0,0.0
26,26,gpt-3.5-turbo-0125,a golf club,0.032936,0.010000,0.000000,0.990000,1.0,0.0
0,0,gpt-3.5-turbo-0125,beer,0.070468,0.003546,0.007092,0.989362,1.0,0.0
21,21,gpt-3.5-turbo-0125,a bookshop,0.119216,0.018293,0.000000,0.981707,1.0,0.0
25,25,gpt-3.5-turbo-0125,a weightlifting class,0.275185,0.024896,0.004149,0.970954,1.0,0.0
19,19,gpt-3.5-turbo-0125,a science museum,0.150141,0.016949,0.016949,0.966102,1.0,0.0
48,48,gpt-4-0613,an art gallery,0.227722,0.020202,0.040404,0.939394,1.0,0.0
34,34,gpt-4-0613,a car,0.009326,0.000000,0.066667,0.933333,1.0,0.0
2,2,gpt-3.5-turbo-0125,ice cream,0.417766,0.061538,0.010256,0.928205,1.0,0.0
18,18,gpt-3.5-turbo-0125,nappies,0.959865,0.083192,0.003396,0.913413,1.0,0.0

In [91]:
Role_metrics[(Role_metrics['model']=='gpt-4-0613') & (Role_metrics['genbit_score']>1.5)]

,Unnamed: 0,model,product,genbit_score,percentage_of_female_gender_definition_words,percentage_of_male_gender_definition_words,percentage_of_non_binary_gender_definition_words,percentage_of_trans_gender_definition_words,percentage_of_cis_gender_definition_words
38,38,gpt-4-0613,furniture polish,1.52221,0.750000,0.005682,0.244318,1.0,0.0
43,43,gpt-4-0613,bubble bath,2.07156,0.901907,0.000000,0.098093,1.0,0.0

## Plot Overall Statistics by Model

### Distribution of Genbit Scores

In [92]:
fig = px.box(Role_metrics, x="model", y = "genbit_score", points="all", hover_data=["product"], 
             title="Distribution of Genbit Score by Model", category_orders={'model':['Gemini AI','gpt-3.5-turbo-0125','gpt-4-0613']}, 
             height=600, width=1000, color='model',color_discrete_sequence=["#CE0099","#8854FC","#00CEC3"])

fig.update_layout(font=dict(size=18))

fig.show()

### Female v Male Words

In [93]:
female_words = Role_metrics.pivot(index="product",columns="model",values="percentage_of_female_gender_definition_words").sort_values(by=["gpt-4-0613"],ascending=False)
male_words = Role_metrics.pivot(index="product",columns="model",values="percentage_of_male_gender_definition_words").sort_values(by=["gpt-4-0613"],ascending=False)
non_binary_words = Role_metrics.pivot(index="product",columns="model",values="percentage_of_non_binary_gender_definition_words").sort_values(by=["gpt-4-0613"],ascending=False)

In [94]:
#Pandas_Bokeh requires a patch to function:
#https://github.com/PatrikHlobil/Pandas-Bokeh/issues/128#issuecomment-1535794247

In [95]:
import pandas
import pandas_bokeh

female_plot = female_words[0:10].sort_values(by=["gpt-3.5-turbo-0125"],ascending=True).plot_bokeh.barh(
                          y=["gpt-3.5-turbo-0125","gpt-4-0613","Gemini AI"],
                        xlabel="Percentage of Female Definition Words",ylabel="Role", 
                        title="Percentage of Female Words",
                        figsize=(500,500),
                        colormap = ["#00CEC3","#8854FC","#CE0099"],
                        legend = "bottom_right",
                        fontsize_label="10pt",
                        fontsize_ticks="10pt",
                        fontsize_title="12pt",
                        show_figure=False
                          )

In [96]:
male_plot = male_words[0:10].sort_values(by=["gpt-3.5-turbo-0125"],ascending=True).plot_bokeh.barh(
                          y=["gpt-3.5-turbo-0125","gpt-4-0613","Gemini AI"],
                        xlabel="Percentage of Male Definition Words",ylabel="Role", 
                        title="Percentage of Male Words",
                        figsize=(500,500),
                        colormap = ["#00CEC3","#8854FC","#CE0099"],
                        legend = "bottom_right",
                        fontsize_label="10pt",
                        fontsize_ticks="10pt",
                        fontsize_title="12pt",
                        show_figure=False
                          )

In [97]:
non_binary_plot = non_binary_words[0:10].sort_values(by=["gpt-4-0613"],ascending=True).plot_bokeh.barh(
                          y=["gpt-3.5-turbo-0125","gpt-4-0613","Gemini AI"],
                        xlabel="Percentage of Non-Binary Definition Words",ylabel="Role", 
                        title="Percentage of Non-Binary Words",
                        figsize=(500,500),
                        colormap = ["#00CEC3","#8854FC","#CE0099"],
                        legend = "bottom_right",
                        fontsize_label="10pt",
                        fontsize_ticks="10pt",
                        fontsize_title="12pt",
                        show_figure=False
                          )

In [98]:
pandas_bokeh.plot_grid([[female_plot,male_plot,non_binary_plot]])

/Users/sandro.rodriguez/Documents/gender-and-generative-ai/venv/lib/python3.9/site-packages/pandas_bokeh/base.py:90: UserWarning:

found multiple competing values for 'toolbar.active_scroll' property; using the latest value

GridPlot(id='p1688', ...)